In [5]:
def fullname(first_name, last_name): # it is a function which takes first name & last name as parameters
    """
    Returns the full name by concatenating first and last name.
    """
    return first_name + " " + last_name


def string_alternative(s): # this function takes only one parameter that is 's'
    """
    Returns a string with every other character from the input string.
    """
    return s[::2] # this is a slicing operation where it prints every other character


def main():
    # Take input from the user
    first_name = input("Enter first name: ")
    last_name = input("Enter last name: ")

    # Get full name
    full_name = fullname(first_name, last_name)
    print("Full Name:", full_name)

    # Get alternate characters
    result = string_alternative(full_name)
    print("String Alternative:", result)


# Call main function
if __name__ == "__main__":
    main()


Enter first name: Varsha
Enter last name: Palamuri
Full Name: Varsha Palamuri
String Alternative: Vrh aaui


In [10]:
%%writefile input.txt
Python Course
Deep Learning Course

Overwriting input.txt


In [17]:
# Step 1: Ask user for number of lines
n = int(input("Enter number of lines: "))

# Step 2: Take user input and store in input.txt
with open("input.txt", "w") as file:
    for i in range(n):
        line = input(f"Enter line {i+1}: ")
        file.write(line + "\n")

# Step 3: Read input.txt
with open("input.txt", "r") as file:
    lines = file.readlines()

# Step 4: Count words
word_count = {}

for line in lines:
    words = line.strip().split()
    for word in words:
        word_count[word] = word_count.get(word, 0) + 1

# Step 5: Write output to output.txt
with open("output.txt", "w") as file:
    for line in lines:
        file.write(line)

    file.write("\nWord_Count:\n")
    for word, count in word_count.items():
        file.write(f"{word}: {count}\n")

# Step 6: Print output
print("\nOutput:")
print("".join(lines))
print("Word_Count:")
for word, count in word_count.items():
    print(f"{word}: {count}")


Enter number of lines: 2
Enter line 1: python Course
Enter line 2: Machine learning 

Output:
python Course
Machine learning 

Word_Count:
python: 1
Course: 1
Machine: 1
learning: 1


In [18]:
# Read heights from user
n = int(input("Enter number of customers: "))
heights_inches = []

for i in range(n):
    height = float(input(f"Enter height of customer {i+1} in inches: "))
    heights_inches.append(height)


# Method 1: Nested Iterative Loop

heights_cm_loop = []

for h in heights_inches:
    cm = h * 2.54
    heights_cm_loop.append(round(cm, 2))

print("\nConverted heights using Nested Loop:")
print(heights_cm_loop)


# Method 2: List Comprehension

heights_cm_comp = [round(h * 2.54, 2) for h in heights_inches]

print("\nConverted heights using List Comprehension:")
print(heights_cm_comp)


Enter number of customers: 2
Enter height of customer 1 in inches: 6.2
Enter height of customer 2 in inches: 5.5

Converted heights using Nested Loop:
[15.75, 13.97]

Converted heights using List Comprehension:
[15.75, 13.97]


In [19]:
class Employee():
    # create data members to track count of employee and list of salaries
    emp_count = 0
    # constructor for initializing the variables
    def __init__(self,name,family,salary,department):
        self.name = name,
        self.family = family,
        self.salary = salary,
        self.department = department,
        Employee.emp_count += 1

    # funtion to return average of salary
    def avg_salary(employees:list):
        salaries_list = [emp.salary[0] for emp in employees] # method 1 : generic
        # print(emp.salary[0] for emp in employees)
        avg_sal = sum(salaries_list)/Employee.emp_count      # method 2 : using numpy
        # avg_sal = np.mean(salaries_list)
        return avg_sal

# create FullTimeEmployee class and inherit the properties from Employee class
class FullTimeEmployee(Employee):
    def __init__(self,name,family,salary,department):
        # calling parent class constructor
        super().__init__(name,family,salary,department)

employees = []
employees.append(Employee("Kumar","Yarva",1000000,"Data Science"))
employees.append(Employee("Ganesh","Aluru",2000000,"Data Analytics"))
employees.append(FullTimeEmployee("Renuka Reddy","Pullalarevu",500000,"Artificial Intelligence"))
employees.append(FullTimeEmployee("Manoj Reddy","Pullalarevu",600000,"Marketing"))


print("Output using employee class : ",  Employee.avg_salary(employees))
print("Output using fulltime employee class : ",FullTimeEmployee.avg_salary(employees))

Output using employee class :  1025000.0
Output using fulltime employee class :  1025000.0


In [1]:
import numpy as np
arr = np.random.uniform(1,20,20) # Random Vector creation of size 20 in the range of 1 - 20.
arr = arr.reshape(4,5) # reshaping the vector to array of (4,5) shape

In [26]:
# Task : replace the max in each row by 0 (axis = 1)
import numpy as np
# Array before replacement
print("Array before replacement :\n\n",arr,end="\n\n\n")

# getting max elements of each row and reshaping it
each_row_max = np.max(arr,axis = 1).reshape(-1,1)

arr[arr == each_row_max] = 0

# print array after replacement
print("Array after replacing the max element of each row with 0: \n\n", arr)

Array before replacement :

 [[12.94217985 11.67438322  0.          9.98078526  9.62316014]
 [ 0.          4.1477846  10.20647951  4.96743371  9.00760323]
 [ 0.         11.45299873 12.46678529  8.99693386 15.21880995]
 [ 0.         17.51578466  4.55226286 12.72141636 11.92667199]]


Array after replacing the max element of each row with 0: 

 [[ 0.         11.67438322  0.          9.98078526  9.62316014]
 [ 0.          4.1477846   0.          4.96743371  9.00760323]
 [ 0.         11.45299873 12.46678529  8.99693386  0.        ]
 [ 0.          0.          4.55226286 12.72141636 11.92667199]]
